"""email, calendar and calls

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 20:18:14.534284
"""

import sqlalchemy as sa
from alembic import op

NEW_TASK_KINDS = ("send_email", "book_meeting", "place_call", "summarize_call")


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.Enum('prescreen', 'schedule', 'reminder', name='callpurpose'), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'queued', 'dialing', 'in_progress', 'completed', 'no_answer', 'declined', 'failed', 'canceled', name='callstatus'), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_sid', sa.String(length=64), nullable=True),
    sa.Column('to_number', sa.String(length=50), nullable=True),
    sa.Column('relay_token', sa.String(length=64), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=200), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_provider_sid'), ['provider_sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('outreach', 'invitation', 'calendar_invite', name='messagekind'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'queued', 'sent', 'failed', name='messagestatus'), nullable=False),
    sa.Column('to', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_by', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_application_id'), ['application_id'], unique=False)

    # Postgres stores task kinds as a native enum; SQLite stores plain strings.
    if op.get_bind().dialect.name == "postgresql":
        for kind in NEW_TASK_KINDS:
            op.execute(f"ALTER TYPE taskkind ADD VALUE IF NOT EXISTS '{kind}'")

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('do_not_call', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interviewer_emails', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('interviewer_emails')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('do_not_call')

    # Postgres can't drop enum values; the extra task kinds are left in place (harmless).
    op.execute("DELETE FROM agent_tasks WHERE kind IN ('send_email', 'book_meeting', 'place_call', 'summarize_call')")

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_application_id'))

    op.drop_table('messages')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_status'))
        batch_op.drop_index(batch_op.f('ix_calls_provider_sid'))
        batch_op.drop_index(batch_op.f('ix_calls_application_id'))

    op.drop_table('calls')
    if op.get_bind().dialect.name == "postgresql":
        for name in ("callpurpose", "callstatus", "messagekind", "messagestatus"):
            op.execute(f"DROP TYPE IF EXISTS {name}")
    # ### end Alembic commands ###
